### PR TITLE
[REVIEW]gQuant 1.0.2

### PR DESCRIPTION
**Pull request by yidong72**

### CODE REVIEW

**Comment by avolkov1** [comment]
Can you regenerate/update the CHANGELOG.md file.
```
github_changelog_generator --future-release=v1.0.2 --release-branch=develop -u NVIDIA -p fsi-samples
```

I generated one and it should look something like this (abbreviated at the end):

# Changelog

## [v1.0.2](https://github.com/NVIDIA/fsi-samples/tree/v1.0.2) (2021-02-11)

[Full Changelog](https://github.com/NVIDIA/fsi-samples/compare/v1.0.1...v1.0.2)

**Merged pull requests:**

- \[REVIEW\]Upgrade the plugin to JupyterLab 3 [\#114](https://github.com/NVIDIA/fsi-samples/pull/114) ([yidong72](https://github.com/yidong72))

## [v1.0.1](https://github.com/NVIDIA/fsi-samples/tree/v1.0.1) (2021-01-20)

[Full Changelog](https://github.com/NVIDIA/fsi-samples/compare/v1.0.0...v1.0.1)

**Merged pull requests:**

- \[REVIEW\]gquant 1.0.1 [\#115](https://github.com/NVIDIA/fsi-samples/pull/115) ([yidong72](https://github.com/yidong72))

## [v1.0.0](https://github.com/NVIDIA/fsi-samples/tree/v1.0.0) (2020-12-30)

[Full Changelog](https://github.com/NVIDIA/fsi-samples/compare/0.5...v1.0.0)

**Closed issues:**

- \[FEA\]We need Plugin file support [\#106](https://github.com/NVIDIA/fsi-samples/issues/106)
- \[FEA\]Migrate to the new input/output port API [\#97](https://github.com/NVIDIA/fsi-samples/issues/97)
- \[FEA\]Add the gQuant Web UI [\#95](https://github.com/NVIDIA/fsi-samples/issues/95)
- \[DOC\] Add CHANGELOG.md [\#48](https://github.com/NVIDIA/fsi-samples/issues/48)

**Merged pull requests:**

- \[REVIEW\]gQuant plugin implementation [\#112](https://github.com/NVIDIA/fsi-samples/pull/112) ([yidong72](https://github.com/yidong72))
- Gpuciscripts clean and update [\#111](https://github.com/NVIDIA/fsi-samples/pull/111) ([msadang](https://github.com/msadang))
- \[REVIEW\] gQuant 1.0 [\#110](https://github.com/NVIDIA/fsi-samples/pull/110) ([yidong72](https://github.com/yidong72))
- Streamz gQuant example 2 [\#109](https://github.com/NVIDIA/fsi-samples/pull/109) ([yidong72](https://github.com/yidong72))
- Revert "Streamz gQuant example" [\#108](https://github.com/NVIDIA/fsi-samples/pull/108) ([yidong72](https://github.com/yidong72))
- Streamz gQuant example [\#107](https://github.com/NVIDIA/fsi-samples/pull/107) ([yidong72](https://github.com/yidong72))
- Bump node-fetch from 2.6.0 to 2.6.1 in /gquantlab [\#104](https://github.com/NVIDIA/fsi-samples/pull/104) ([dependabot[bot]](https://github.com/apps/dependabot))
- Nemo and xgboost integration  [\#103](https://github.com/NVIDIA/fsi-samples/pull/103) ([yidong72](https://github.com/yidong72))
- FIX Update change log check [\#102](https://github.com/NVIDIA/fsi-samples/pull/102) ([mike-wendt](https://github.com/mike-wendt))
- \[REVIEW\] Update CI scripts to remove references to master \[skip ci\] [\#99](https://github.com/NVIDIA/fsi-samples/pull/99) ([dillon-cullinan](https://github.com/dillon-cullinan))
- \[skip ci\] Update master references for main branch [\#98](https://github.com/NVIDIA/fsi-samples/pull/98) ([ajschmidt8](https://github.com/ajschmidt8))
- \[REVIEW\]gQuant UI, first version [\#89](https://github.com/NVIDIA/fsi-samples/pull/89) ([yidong72](https://github.com/yidong72))

.
.
.

**Comment by yidong72** [comment]
Thanks for 

> Can you regenerate/update the CHANGELOG.md file.
> 
> ```
> github_changelog_generator --future-release=v1.0.2 --release-branch=develop -u NVIDIA -p fsi-samples
> ```
> 
> I generated one and it should look something like this (abbreviated at the end):
> 
> # Changelog
> ## [v1.0.2](https://github.com/NVIDIA/fsi-samples/tree/v1.0.2) (2021-02-11)
> [Full Changelog](https://github.com/NVIDIA/fsi-samples/compare/v1.0.1...v1.0.2)
> 
> **Merged pull requests:**
> 
> * [REVIEW]Upgrade the plugin to JupyterLab 3 [#114](https://github.com/NVIDIA/fsi-samples/pull/114) ([yidong72](https://github.com/yidong72))
> 
> ## [v1.0.1](https://github.com/NVIDIA/fsi-samples/tree/v1.0.1) (2021-01-20)
> [Full Changelog](https://github.com/NVIDIA/fsi-samples/compare/v1.0.0...v1.0.1)
> 
> **Merged pull requests:**
> 
> * [REVIEW]gquant 1.0.1 [#115](https://github.com/NVIDIA/fsi-samples/pull/115) ([yidong72](https://github.com/yidong72))
> 
> ## [v1.0.0](https://github.com/NVIDIA/fsi-samples/tree/v1.0.0) (2020-12-30)
> [Full Changelog](https://github.com/NVIDIA/fsi-samples/compare/0.5...v1.0.0)
> 
> **Closed issues:**
> 
> * [FEA]We need Plugin file support [#106](https://github.com/NVIDIA/fsi-samples/issues/106)
> * [FEA]Migrate to the new input/output port API [#97](https://github.com/NVIDIA/fsi-samples/issues/97)
> * [FEA]Add the gQuant Web UI [#95](https://github.com/NVIDIA/fsi-samples/issues/95)
> * [DOC] Add CHANGELOG.md [#48](https://github.com/NVIDIA/fsi-samples/issues/48)
> 
> **Merged pull requests:**
> 
> * [REVIEW]gQuant plugin implementation [#112](https://github.com/NVIDIA/fsi-samples/pull/112) ([yidong72](https://github.com/yidong72))
> * Gpuciscripts clean and update [#111](https://github.com/NVIDIA/fsi-samples/pull/111) ([msadang](https://github.com/msadang))
> * [REVIEW] gQuant 1.0 [#110](https://github.com/NVIDIA/fsi-samples/pull/110) ([yidong72](https://github.com/yidong72))
> * Streamz gQuant example 2 [#109](https://github.com/NVIDIA/fsi-samples/pull/109) ([yidong72](https://github.com/yidong72))
> * Revert "Streamz gQuant example" [#108](https://github.com/NVIDIA/fsi-samples/pull/108) ([yidong72](https://github.com/yidong72))
> * Streamz gQuant example [#107](https://github.com/NVIDIA/fsi-samples/pull/107) ([yidong72](https://github.com/yidong72))
> * Bump node-fetch from 2.6.0 to 2.6.1 in /gquantlab [#104](https://github.com/NVIDIA/fsi-samples/pull/104) ([dependabot[bot]](https://github.com/apps/dependabot))
> * Nemo and xgboost integration  [#103](https://github.com/NVIDIA/fsi-samples/pull/103) ([yidong72](https://github.com/yidong72))
> * FIX Update change log check [#102](https://github.com/NVIDIA/fsi-samples/pull/102) ([mike-wendt](https://github.com/mike-wendt))
> * [REVIEW] Update CI scripts to remove references to master [skip ci] [#99](https://github.com/NVIDIA/fsi-samples/pull/99) ([dillon-cullinan](https://github.com/dillon-cullinan))
> * [skip ci] Update master references for main branch [#98](https://github.com/NVIDIA/fsi-samples/pull/98) ([ajschmidt8](https://github.com/ajschmidt8))
> * [REVIEW]gQuant UI, first version [#89](https://github.com/NVIDIA/fsi-samples/pull/89) ([yidong72](https://github.com/yidong72))
> 
> .
> .
> 
Thanks for providing the command to update the changelog. I generated it

**Comment by avolkov1** [comment]
Last time I merged develop into main I messed up slightly and did a squash merge. Now that causes main to appear as ahead of develop by one commit:
https://github.com/NVIDIA/fsi-samples/compare/develop...main

I'm going to make a PR and merge main into develop to synchronize the branches. Then I'll merge this PR.

**Comment by avolkov1** [comment]
I synchronized the develop branch with main. Now everything looks good and develop appears ahead of main correctly.
In general I do squash merges for forked branches into develop. But when merging develop into main it should be done with regular merge. It was my mess up, sorry about that.

**Comment by yidong72** [comment]
> I synchronized the develop branch with main. Now everything looks good and develop appears ahead of main correctly.
> In general I do squash merges for forked branches into develop. But when merging develop into main it should be done with regular merge. It was my mess up, sorry about that.

No worry. It looks good.

**Review by avolkov1 — APPROVED** [review]
Looks good. I'll merge this.

**Pull request merged**
